name: CI

on:
  push:
    branches: [main-overdese]
    tags: ['*']
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      - name: Install Build Dependencies
        run: |
          brew install libvncserver
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          cmake --install .
      - name: Ad-hoc Code Sign
        run: |
          codesign --force --deep -s - build/*.app
      - name: Archive App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: macVNC App Bundle
          path: build/*.app
